import Navbar from "../components/shared/navbar";
import Footer from "../components/shared/footer";
import "./globals.css";
import {Poppins} from "next/font/google"

const poppins = Poppins ({
  weight:["400","500","600"],
  style:["normal","italic"],
  subsets:["latin"]
})

export const metadata = {
  title: "Kalisa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          {/* <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          /> */}
        </head>
        <body>
          <div className={poppins.className}>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
