import Navbar from "../components/shared/navbar";
import Footer from "../components/shared/footer";
import "./globals.css";

export const metadata = {
  title: "Kalisa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
        </head>
        <body>
          <div>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
